site_name: Doc test
site_description: VIP is a flexible human variant interpretation pipeline for rare disease using state-of-the-art pathogenicity prediction (CAPICE) and template-based interactive reporting to facilitate decision support.
site_url: https://github.com/bartcharbon/dataconversion-tools/
repo_url: https://github.com/bartcharbon/dataconversion-tools/
nav:
  - 'Home':
    - 'Introduction': 'docs/index.md'
    - 'Key features': 'docs/home/key_features.md'
  - 'Get Started':
    - 'Requirements': 'docs/get_started/requirements.md'
    - 'Installation': 'docs/get_started/installation.md'
    - 'Start running': 'docs/get_started/start_running.md'
  - 'Usage':
      - 'Command-line options': 'docs/usage/command-line-options.md'
      - 'Workflow': 'docs/usage/workflow.md'
      - 'Input': 'docs/usage/input.md'
      - 'Output': 'docs/usage/output.md'
      - 'Config': 'docs/usage/config.md'
  - 'Examples':
      - 'Nanopore': 'docs/examples/nanopore.md'
      - 'Multi-project': 'docs/examples/multi-project.md'
      - 'Reanalysis': 'docs/examples/reanalysis.md'
  - 'Advanced':
      - 'Annotationss': 'docs/advanced/annotations.md'
      - 'Classification trees': 'docs/advanced/classification_trees.md'
      - 'Report templates': 'docs/advanced/report_templates.md'
  - 'Help':
       - 'Issues': 'docs/help/issues.md'
       - 'Frequently asked questions': 'docs/help/frequently_asked_questions.md'
  - 'About':
    - 'License': 'docs/about/license.md'
    - 'Acknowledgements': 'docs/about/acknowledgements.md'
markdown_extensions:
  - admonition
  - toc:
      permalink: True
plugins:
  - search
  - mermaid2
theme: readthedocs
strict: true
extra_css: [custom.css]
extra_javascript: [js/mermaid.min.js]
copyright: Copyright © 2023 University Medical Center Groningen All rights reserved